// Mocks generated by Mockito 5.4.5 from annotations
// in angry_raphi/test/features/raphcon_management/domain/usecases/get_user_raphcon_statistics_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:angry_raphi/core/enums/raphcon_type.dart' as _i7;
import 'package:angry_raphi/core/errors/failures.dart' as _i5;
import 'package:angry_raphi/features/raphcon_management/domain/entities/raphcon_entity.dart'
    as _i6;
import 'package:angry_raphi/features/raphcon_management/domain/repositories/raphcons_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RaphconsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRaphconsRepository extends _i1.Mock
    implements _i3.RaphconsRepository {
  MockRaphconsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.RaphconEntity>>> getUserRaphcons(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserRaphcons, [userId]),
            returnValue: _i4.Future<
              _i2.Either<_i5.Failure, List<_i6.RaphconEntity>>
            >.value(
              _FakeEither_0<_i5.Failure, List<_i6.RaphconEntity>>(
                this,
                Invocation.method(#getUserRaphcons, [userId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.RaphconEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.RaphconEntity>>>
  getUserRaphconsByType(String? userId, _i7.RaphconType? type) =>
      (super.noSuchMethod(
            Invocation.method(#getUserRaphconsByType, [userId, type]),
            returnValue: _i4.Future<
              _i2.Either<_i5.Failure, List<_i6.RaphconEntity>>
            >.value(
              _FakeEither_0<_i5.Failure, List<_i6.RaphconEntity>>(
                this,
                Invocation.method(#getUserRaphconsByType, [userId, type]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.RaphconEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.RaphconEntity>>>
  getAllRaphcons() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRaphcons, []),
            returnValue: _i4.Future<
              _i2.Either<_i5.Failure, List<_i6.RaphconEntity>>
            >.value(
              _FakeEither_0<_i5.Failure, List<_i6.RaphconEntity>>(
                this,
                Invocation.method(#getAllRaphcons, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.RaphconEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> addRaphcon(
    _i3.AddRaphconParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addRaphcon, [params]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#addRaphcon, [params]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteRaphcon(String? raphconId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRaphcon, [raphconId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteRaphcon, [raphconId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Stream<_i2.Either<_i5.Failure, List<_i6.RaphconEntity>>>
  getUserRaphconsStream(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserRaphconsStream, [userId]),
            returnValue:
                _i4.Stream<
                  _i2.Either<_i5.Failure, List<_i6.RaphconEntity>>
                >.empty(),
          )
          as _i4.Stream<_i2.Either<_i5.Failure, List<_i6.RaphconEntity>>>);

  @override
  _i4.Stream<_i2.Either<_i5.Failure, List<_i6.RaphconEntity>>>
  getUserRaphconsByTypeStream(String? userId, _i7.RaphconType? type) =>
      (super.noSuchMethod(
            Invocation.method(#getUserRaphconsByTypeStream, [userId, type]),
            returnValue:
                _i4.Stream<
                  _i2.Either<_i5.Failure, List<_i6.RaphconEntity>>
                >.empty(),
          )
          as _i4.Stream<_i2.Either<_i5.Failure, List<_i6.RaphconEntity>>>);

  @override
  _i4.Stream<_i2.Either<_i5.Failure, List<_i6.RaphconEntity>>>
  getAllRaphconsStream() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRaphconsStream, []),
            returnValue:
                _i4.Stream<
                  _i2.Either<_i5.Failure, List<_i6.RaphconEntity>>
                >.empty(),
          )
          as _i4.Stream<_i2.Either<_i5.Failure, List<_i6.RaphconEntity>>>);
}
