// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// ⚠️ SECURITY NOTE:
/// These Firebase API keys are safe to commit to version control.
/// They are client identifiers, not authentication credentials.
/// Security is enforced by:
/// - Firestore Security Rules (see firestore.rules)
/// - Firebase Authentication
/// - API restrictions in Firebase Console
///
/// For more information, see SECURITY.md
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9wEj8rCnI9bCmcsh39B5SpQTnXzgQKQw',
    appId: '1:733842826620:web:1297526ba92a4820cf70f9',
    messagingSenderId: '733842826620',
    projectId: 'angryraphi',
    authDomain: 'angryraphi.firebaseapp.com',
    storageBucket: 'angryraphi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmaAak4x-WapSf9-uys0hAbn7hKErrry0',
    appId: '1:733842826620:android:c35cdb0ab78268cdcf70f9',
    messagingSenderId: '733842826620',
    projectId: 'angryraphi',
    storageBucket: 'angryraphi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9iH7IX5ec7fbVMZu3RYjAgMAIdRRNdNQ',
    appId: '1:733842826620:ios:8e29f5acaedeb0edcf70f9',
    messagingSenderId: '733842826620',
    projectId: 'angryraphi',
    storageBucket: 'angryraphi.firebasestorage.app',
    iosClientId: '733842826620-p8ls9c32sc5s6g9ufat2o95mg4ujgqeh.apps.googleusercontent.com',
    iosBundleId: 'com.angryraphi.angryRaphi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:123456789:ios:xxxxxxxxxxxxxxxxx',
    messagingSenderId: '123456789',
    projectId: 'angryraphi',
    storageBucket: 'angryraphi.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9wEj8rCnI9bCmcsh39B5SpQTnXzgQKQw',
    appId: '1:733842826620:web:2587dd68732ee212cf70f9',
    messagingSenderId: '733842826620',
    projectId: 'angryraphi',
    authDomain: 'angryraphi.firebaseapp.com',
    storageBucket: 'angryraphi.firebasestorage.app',
  );

}