// Mocks generated by Mockito 5.4.5 from annotations
// in angry_raphi/test/features/admin/presentation/bloc/admin_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:angry_raphi/core/errors/failures.dart' as _i6;
import 'package:angry_raphi/features/admin/domain/repositories/admin_repository.dart'
    as _i2;
import 'package:angry_raphi/features/admin/domain/usecases/add_admin.dart'
    as _i7;
import 'package:angry_raphi/features/admin/domain/usecases/check_admin_status.dart'
    as _i4;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAdminRepository_0 extends _i1.SmartFake
    implements _i2.AdminRepository {
  _FakeAdminRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CheckAdminStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckAdminStatus extends _i1.Mock implements _i4.CheckAdminStatus {
  MockCheckAdminStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AdminRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAdminRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AdminRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> call(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#call, [email]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
              _FakeEither_1<_i6.Failure, bool>(
                this,
                Invocation.method(#call, [email]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, bool>>);
}

/// A class which mocks [AddAdmin].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddAdmin extends _i1.Mock implements _i7.AddAdmin {
  MockAddAdmin() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AdminRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAdminRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AdminRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call({
    required String? userId,
    required String? email,
    required String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #userId: userId,
              #email: email,
              #displayName: displayName,
            }),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#call, [], {
                  #userId: userId,
                  #email: email,
                  #displayName: displayName,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);
}
