// Mocks generated by Mockito 5.4.5 from annotations
// in angry_raphi/test/features/authentication/data/models/user_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:cloud_firestore_platform_interface/src/timestamp.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Timestamp].
///
/// See the documentation for Mockito's code generation for more information.

class MockTimestamp extends _i1.Mock implements _i2.Timestamp {
  MockTimestamp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get seconds =>
      (super.noSuchMethod(Invocation.getter(#seconds), returnValue: 0) as int);

  @override
  int get nanoseconds =>
      (super.noSuchMethod(Invocation.getter(#nanoseconds), returnValue: 0)
          as int);

  @override
  int get millisecondsSinceEpoch =>
      (super.noSuchMethod(
            Invocation.getter(#millisecondsSinceEpoch),
            returnValue: 0,
          )
          as int);

  @override
  int get microsecondsSinceEpoch =>
      (super.noSuchMethod(
            Invocation.getter(#microsecondsSinceEpoch),
            returnValue: 0,
          )
          as int);

  @override
  DateTime toDate() =>
      (super.noSuchMethod(
            Invocation.method(#toDate, []),
            returnValue: _FakeDateTime_0(this, Invocation.method(#toDate, [])),
          )
          as DateTime);

  @override
  int compareTo(_i2.Timestamp? other) =>
      (super.noSuchMethod(
            Invocation.method(#compareTo, [other]),
            returnValue: 0,
          )
          as int);
}
