// Mocks generated by Mockito 5.4.5 from annotations
// in angry_raphi/test/features/user/presentation/bloc/user_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:angry_raphi/features/user/domain/entities/user.dart' as _i4;
import 'package:angry_raphi/features/user/domain/usecases/user_usecases.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetUsersUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUsersUseCase extends _i1.Mock implements _i2.GetUsersUseCase {
  MockGetUsersUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.User>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i3.Future<List<_i4.User>>.value(<_i4.User>[]),
          )
          as _i3.Future<List<_i4.User>>);
}

/// A class which mocks [GetUsersStreamUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUsersStreamUseCase extends _i1.Mock
    implements _i2.GetUsersStreamUseCase {
  MockGetUsersStreamUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.User>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i3.Stream<List<_i4.User>>.empty(),
          )
          as _i3.Stream<List<_i4.User>>);
}

/// A class which mocks [AddUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddUserUseCase extends _i1.Mock implements _i2.AddUserUseCase {
  MockAddUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> execute(_i4.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [user]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [DeleteUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteUserUseCase extends _i1.Mock implements _i2.DeleteUserUseCase {
  MockDeleteUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> execute(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [userId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
